### ISSUE TITLE
[Suggestion] Adding Opening Comics to the start of levels and other storyboarding options

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [GDQuest/godot-2d-rhythm#4]
**I'm submitting a...**
- [ ] Bug report.
- [X] Feature request.

## Feature request ##

**Describe the problem you're trying to solve.**
Well, it's not exactly a problem, but it is something I'm interested in seeing from this project considering it's an Elite Beat Agents/Ouendan clone. Something I liked about those games is that each stage had it's on scenario which was accompanied by it's own comic/manga which would play out before you went into each stage and a storyboard (essentially an animated background that went with each beatmap. Having a playable game is okay, but being able to use that game to tell a story would be fantastic.

I want a system that, despite being complicated to set up, would streamline the importing and animation of assets to create these storyboards and opening comics.
**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**
I'm fairly new to Godot, so I wouldn't even know where to begin.
## Other ##

**Other information** 
This is some gameplay footage of Elite Beat Agents to help (or should I say HEEEAAALP) illustrate my point: https://www.youtube.com/watch?v=9zd4So-gFoE&t=475s

**Comment by NathanLovato** [comment]
We're not adding features to the project at this point, only leaving issues for bug reports.

Note that you can do what you'd like by creating an animation with the animation player node. All you then need is the illustrations. You don't need any particular plug-in or system.

**Comment by TheNamesGregoryAndounuts** [comment]
Certainly would help.
