### ISSUE TITLE
error: at the top left of screen

### ISSUE THREAD

**Issue by Techno274721** [GDQuest/godot-2d-rhythm#5]
**I'm submitting a...**

- [x ] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
when i run it with godot i tkeeps appearing on the top left of my screen and it hides most of the rythm sample

**What is the expected behavior?**
to be around thecenter of the screen or elsewhere but not popping out of the screen

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1.press run
2.game loads and it is stuck at the top left of the screen

**Comment by cogwoz** [comment]
I can't reproduce this. Can you supply a screenshot?

**Comment by Techno274721** [comment]
![image](https://user-images.githubusercontent.com/79793414/161510835-0830bdfe-f693-4a37-bdb9-c072611d3ddc.png)

**Comment by NathanLovato** [comment]
It's not an issue with this project specifically. It depends on your display, system, display settings... It may just be that the window resolution (1920x1080) is too large for your system, or that with the system display scaling it gets offset a bit.

You should be able to address that by going to project -> project settings... -> display -> window, and setting it to fullscreen or by changing the test width and test height.
